/** Human-readable column titles (same order as ANALYSIS_ROW_CELL_KEYS / Excel export). */
export const EXPORT_HEADERS = [
  'Move Number',
  'Turn',
  'SAN Move',
  'UCI Move',
  'Clock',
  'Played Move Classification',
  'Played Move Standing',
  'Played Move Evaluation',
  'Evaluation (Before Move)',
  'Move Quality (Delta)',
  'Best Line Delta',
  'Win % (White)',
  'FEN (Before Move)',
  'FEN (After Move)',
  'Legal Moves (At Move)',
  'Best Move Alternatives (At Move)',
  'Captures',
  'Game Phase',
  'Board Density',
  'White Space Dominance',
  'Black Space Dominance',
  'White Material',
  'Black Material',
  'Material Advantage',
  'Simplification',
  'Hanging Pieces',
  'Loose Pieces',
  'White King Attack Intensity',
  'White King Exposure',
  'Black King Attack Intensity',
  'Black King Exposure',
  'White King Mobility',
  'Black King Mobility',
  'White Pawn Islands',
  'White Doubled Pawns',
  'Black Pawn Islands',
  'Black Doubled Pawns',
  'White Avg Mobility',
  'Black Avg Mobility',
  'White Position Freedom',
  'Black Position Freedom',
  'White Space Controlled',
  'Black Space Controlled',
  'Space Ratio',
  'Pins',
  'Forks',
  'Endgame Proximity',
  'White Practical Risk',
  'Black Practical Risk',
  'Overall Evaluation',
  'Winning Plan',
  'Generated Commentary',
  'Flan-T5 Output',
  'Line 1 Eval',
  'Line 1 Classification',
  'Line 1 Sequence',
  'Line 2 Eval',
  'Line 2 Classification',
  'Line 2 Sequence',
  'Line 3 Eval',
  'Line 3 Classification',
  'Line 3 Sequence',
  'Line 4 Eval',
  'Line 4 Classification',
  'Line 4 Sequence',
  'Line 5 Eval',
  'Line 5 Classification',
  'Line 5 Sequence',
  'Line 6 Eval',
  'Line 6 Classification',
  'Line 6 Sequence',
  'Line 7 Eval',
  'Line 7 Classification',
  'Line 7 Sequence',
  'Line 8 Eval',
  'Line 8 Classification',
  'Line 8 Sequence',
  'Line 9 Eval',
  'Line 9 Classification',
  'Line 9 Sequence',
  'Line 10 Eval',
  'Line 10 Classification',
  'Line 10 Sequence',
];
